### ISSUE TITLE
fs._stringToFlags is not a function

### ISSUE THREAD

**Issue by tknobi** [waywaaard/sandbox-server#1]
I installed and configured the sandbox server. If I open a bash window, I am able to write, compile and run a program. 
But after pressing the "Run" Button I get the following error message:
```
fs._stringToFlags is not a function
```
There is a folder _project1_ but it's empty, so the mkdir command works and the problem seems to be during the writeFile command.

**Comment by ebertmi** [comment]
Wo genau tritt der Fehler auf? Auf der Testseite, im Server-Log, oder woanders?

**Comment by tknobi** [comment]
Er wird auf der Testseite per Javascript Alert und Konsolenlog ausgegeben.

**Comment by ebertmi** [comment]
Okay, ich kann es leider nicht nachvollziehen bzw. reproduzieren. Kannst du mir mal ein paar Infos geben? Gibt es einen StackTrace auf der Konsole? Gibt es serverseitig einen Fehler, wenn du in die Logs schaust. Am besten startest du den Server mit [Debug-Infos](https://github.com/waywaaard/sandbox-server#debugging).

Im Browser kannst du dir detaillierte Debug-Information ausgeben lassen, indem du `localStorage.debug = 'sourcebox:*'` in der Console setzt (z.B. Chrome Dev-Tools).

**Comment by tknobi** [comment]
Sorry für die lange Verzögerung, hab an anderen Stellen weiter gemacht. Jetzt aber nochmal zum Problem:

Das Problem tritt in sourcebox-lxc auf:
https://github.com/waywaaard/sourcebox-lxc/blob/master/lib/lxc.js#L280

DIe Funktion fs._stringToFlags() soll die String Datei Flags (z.B. 'w') in einen Integer wandeln.
In dieses Format: http://man7.org/linux/man-pages/man2/open.2.html

Leider finde ich nirgends eine Doku zu der Funktion. Habe das "gehackt" und zu Testzwecken selbst gewandelt. Dann funktioniert alles.

**Comment by ebertmi** [comment]
Okay, dann weiß ich warum.
Das liegt ziemlich sicher an der nodejs-Version. Die Funktion `_stringToFlags` gibt es nur bis node 4.7.x und wurde dort eigentlich nur für Tests exportiert. In neueren nodejs-Versionen ist das leider nicht mehr der Fall. Weswegen das angepasst werden muss

**Comment by ebertmi** [comment]
Siehe https://github.com/waywaaard/sourcebox-lxc/commit/da37b5e17989b37ac9b17342719b5e5ffb78fec8

Sollte damit auch in nodejs 7 gehen

**Comment by tknobi** [comment]
Jap, funktioniert! Vielen Dank!
